export const SUPABASE_EDGE_FUNCTIONS = {
  ACCESS_EMAIL_SHARED: 'accessEmail_shared',
  CREATE_CLIENT_PROCESS: 'create-client-process',
  CREATE_PROCESS_CLIENT_USER: 'create-process-client-user',
  CREATE_USER: 'create-user',
  DOCUMENT_REVIEW_NOTIFICATION: 'document-review-notification',
  FORGOT_PASSWORD: 'forgot-password',
  SEND_ACCESS_CREDENTIALS: 'send-access-credentials',
  NOTIFY_PROCESS_ASSIGNMENT: 'notify-process-assignment',
  SEND_CERTIFICATE: 'send-certificate',
  STRIPE_CREATE_CHECKOUT_SESSION: 'stripe-create-checkout-session',
  STRIPE_CREATE_CUSTOMER_PORTAL_SESSION: 'stripe-create-customer-portal-session',
  STRIPE_RECONCILIATION: 'stripe-reconciliation',
  WIX_CLIENT_INTAKE: 'wix-client-intake',
  UPDATE_USER_ORG_MEMBERSHIP: 'update-user-org-membership',
} as const;
