import Stripe from 'https://esm.sh/stripe@18.3.0?target=deno';
import { Client } from 'https://deno.land/x/postgres@v0.19.3/mod.ts';
const corsHeaders = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const getDbConnectionString = () => Deno.env.get('SUPABASE_DB_URL') ?? Deno.env.get('POSTGRES_URL') ?? Deno.env.get('DATABASE_URL') ?? '';
const mapStripeToPaymentStatus = (s: Stripe.PaymentIntent.Status): 'pending'|'paid'|'failed'|'canceled' => s==='succeeded'?'paid':s==='canceled'?'canceled':s==='requires_payment_method'?'failed':'pending';
const resolveProcessUpdate = (p:'pending'|'paid'|'failed'|'canceled') => p==='paid'?{processStatus:'liberado',shouldReleaseProcess:true}:{processStatus:null,shouldReleaseProcess:false};
type PendingPayment={id:string;process_id:string;client_id:string;org_id:string;stripe_checkout_session_id:string|null;stripe_payment_intent_id:string|null};
Deno.serve(async (request)=>{ if(request.method==='OPTIONS') return new Response('ok',{headers:corsHeaders}); if(request.method!=='POST') return new Response(JSON.stringify({error:'Método não permitido'}),{status:405,headers:{...corsHeaders,'Content-Type':'application/json'}});
const stripeSecretKey=Deno.env.get('STRIPE_SECRET_KEY')??''; const dbConnectionString=getDbConnectionString(); if(!stripeSecretKey||!dbConnectionString) return new Response(JSON.stringify({error:'Configuração ausente'}),{status:500,headers:{...corsHeaders,'Content-Type':'application/json'}});
const body=await request.json().catch(()=>({})); const staleMinutes=Math.max(10,Math.min(60,Number(body?.staleMinutes??15))); const limit=Math.max(1,Math.min(100,Number(body?.limit??50)));
const stripe=new Stripe(stripeSecretKey,{apiVersion:'2025-03-31.basil'}); const client=new Client(dbConnectionString); const result={scanned:0,updated:0,keptPending:0,errors:0};
try { await client.connect(); const pending=await client.queryObject<PendingPayment>(`SELECT pay.id, pay.process_id, pay.client_id, pr.org_id, pay.stripe_checkout_session_id, pay.stripe_payment_intent_id FROM public.payments pay JOIN public.processes pr ON pr.id = pay.process_id WHERE pay.status = 'pending' AND pay.created_at <= now() - (($1::text || ' minutes')::interval) AND (pay.stripe_payment_intent_id IS NOT NULL OR pay.stripe_checkout_session_id IS NOT NULL) ORDER BY pay.created_at ASC LIMIT $2`,[String(staleMinutes),limit]);
for (const payment of pending.rows){ result.scanned+=1; let paymentIntentId=payment.stripe_payment_intent_id; try { if(!paymentIntentId&&payment.stripe_checkout_session_id){ const session=await stripe.checkout.sessions.retrieve(payment.stripe_checkout_session_id); paymentIntentId=typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id??null; } if(!paymentIntentId){result.keptPending+=1; continue;} const paymentIntent=await stripe.paymentIntents.retrieve(paymentIntentId); const targetStatus=mapStripeToPaymentStatus(paymentIntent.status); if(targetStatus==='pending'){result.keptPending+=1; continue;} await client.queryArray('BEGIN'); await client.queryObject(`UPDATE public.payments SET status = $2, payment_provider = 'stripe', paid_at = CASE WHEN $2 = 'paid' THEN COALESCE(paid_at, now()) ELSE paid_at END, stripe_payment_intent_id = COALESCE($3, stripe_payment_intent_id), last_event_type = 'reconciliation.run', last_event_at = now(), updated_at = now() WHERE id = $1`,[payment.id,targetStatus,paymentIntentId]); const processUpdate=resolveProcessUpdate(targetStatus); if(processUpdate.shouldReleaseProcess){ await client.queryObject(`UPDATE public.processes SET payment_status = $2, process_status = $3, updated_at = now(), usage_deadline_at = COALESCE(usage_deadline_at, now() + interval '30 days') WHERE id = $1`,[payment.process_id,targetStatus,processUpdate.processStatus]); } else { await client.queryObject(`UPDATE public.processes SET payment_status = $2, updated_at = now() WHERE id = $1`,[payment.process_id,targetStatus]); }
await client.queryObject(`INSERT INTO public.process_events (org_id, process_id, tipo, mensagem, correlation_process_id, correlation_checkout_session_id, correlation_stripe_event_id, event_code, event_type) VALUES ($1, $2, 'status_change', $3, $2, $4, $5, 'payment_reconciled', 'payment')`,[payment.org_id,payment.process_id,`Reconciliação Stripe aplicada. status=${targetStatus}; payment_intent=${paymentIntentId}.`,payment.stripe_checkout_session_id,paymentIntentId]); await client.queryArray('COMMIT'); result.updated+=1; } catch(err){ await client.queryArray('ROLLBACK').catch(()=>undefined); console.error('[stripe-reconciliation] erro item',payment.id,err); result.errors+=1; }}
return new Response(JSON.stringify({success:true,...result,staleMinutes,limit}),{headers:{...corsHeaders,'Content-Type':'application/json'}});
} catch(error){ return new Response(JSON.stringify({success:false,error:error instanceof Error?error.message:'Erro interno'}),{status:500,headers:{...corsHeaders,'Content-Type':'application/json'}});} finally { await client.end().catch(()=>undefined);} });
